name = "johnnies-poker"
main = ".output/server/index.mjs"
compatibility_date = "2025-01-01"

[[durable_objects.bindings]]
name = "$DurableObject"
class_name = "$DurableObject"

[[migrations]]
tag = "v1"
new_classes = ["$DurableObject"]
